name: WakaTime Metrics

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install WakaTime CLI
      run: pip install wakatime
    - name: Update Metrics
      env:
        WAKATIME_API_KEY: ${{ secrets.waka_api_key }}
      run: wakatime --entity sultansse --api-key $WAKATIME_API_KEY --write-quietly
    - name: Update README
      uses: jamesgeorge007/github-activity-readme@master
      with:
        token: ${{ secrets.token_github }}
        username: sultansse
        waka-time: true
        show-icons: true
